language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
before_deploy:
- make sphinx
- pip install --upgrade setuptools wheel
- python setup.py sdist bdist_wheel
deploy:
  skip_cleanup: true
  # Deploy Sphinx Docs to Github pages
  provider: pages
  local-dir: docs/build/html
  github-token:
    secure: "ViS44SB+dgdy76HWroef2Ob+BdPFyElERfMxmqGG0mybylAAtF/t9/qZeh5T5pw1E8LHf0cs3ehQwlERABuvW1sbvQ8X5LCOl7nKo0nrXxvWPpLcEaz+K9txIYQ3J+p3bewtCnXP3Tj7+Nluq3C3ialMDwOQlPpaYp00+3tc2eUbfHNnG/2gqHbyhRueeQ/6PN3c6tk6hJMT60+377Y9uT4mM1g32HzPL76TA8WqUO++cz1l1d8jAp6wpV/8F2xyY0s6QH09qviGTENSEYPsE4D35nY2/2/YIrpSk4jkC/Vt8qjeLBzqA0dDYRsTHcMDh8jlXPc7BIHonsHWwiYGWyQ3g7DUZmOQ4pjaJF53h0iW07mr0e5E8MF/clAo5m2oKpSq6vrA77AQZlnlrZOtmfej8+enToO+l6QiBjShfF4v8ZzuJ3wjHiHAaO0iMMaehtVp3K+f7ZOJB8ES5/EKg1DsA2PpFxYVKu68llfEZgVoKC+Ow41oEK9SDi/37KfZ6ycxXgtSPR2DURMpdMYmMQ1BGc9Xn1tgPBUpE0bePqiiar44h/nOnzhF8IZ4SuUJcd2dI4/b/k4PKe3Tq6u9rdK9a2U8Q9QFxnkizIUL4EZ27gPtmV1VdCDAPrieVEgKs8t70djoc04B3+KX+v+npQ2Lps6t9OWGckBvHSIzPF0="
  keep-history: true
  # Deploy PIP package to PyPi
  provider: pypi
  user:
    secure: "Rdd2gRjzPLG5E36PuAb2/hBmodW9BegLarRy0QCjiCc5z0OIcipZe2lN14xjeg8+eDsAPMCCeYEJ8pNNFN1Wv6T9MxCA0aq+X6pJzW1VRrPjskmf8rE2KTvKbHAFy+bbBJNhWz2pybu1MB3tyuASMUyax41wTjocC80XL9GNMCu/sf3oUR2kgk4OpcN1rHw6bNzZoT4qL0riOsA8Go9wP3Q+tEeTxNo9ddn5GQcf2nN/3VdwMrydvJ6MxbAvUpseu/xpTYjL4FhrryevB9b1rlmMqIKIa8iStNsn33UD7PwjhN3XZs0afyKkjsEDhoYCRPUr6MQHP/uQuud98P0nSaw+wgNev8MFKjxzqO8j3iVy5NwDEYlq7e22wt8TJEkMQ4RBb1dzCNsPXvOZj8htGjJFJnQbA4n/SE3ZiO7NtEEFifsenCBN8pQy9MPmXeNrvS2hFgqcZPhngh2thz4pcX9CMQndEe6MfaDAtZDqIfDmKRwYCUpvsMF5SCxPYosY46BYqc/BaFoRLjrAZnUQGvHAXk/D/f5nTaXyaO6Y2dw7EWZyH6NtDQHKQVD4Bpnn2ElQVr0Ro1hXe70CzCcbMGv7BNFDaachtQAJvrLT1Wc6ojIEccLUeJIE4Oq6RuAfeVIRB2c7olXn5KqV82oxikpi98y6GHGaXn/b7ERCqWo="
  password:
    secure: "GDr5QQppH1cytrR2xdHWcXC51lCRaQkiL8fq+rFVii7fHFKcNJWH+CYek0Vxi/dyrvxaRrNByNqmw7ToLEfWvShd+JLyHY+FJQ8OK+DPV0tSGIkruvyUh6f+M6yUtfB94CR5N81NHdlzQ2+MVusxb/Kt9R6eR2lKBbyO3UYSas94WjRmrU9s1Hm6mbkbhBqUeHk88icmBU/teQZYya2e78w6dQOh3idVXjDQGIgBQPgwgeuGkSgai5fv19bqGWCEC872hQdoaFWNVvnETlA0MDuUopvyibw1vd9sHV6NxEso5rdjrbSMqzIz7qbVYoqGAmShOfUFjC5yWYpbU5RrHmRiahV0fulhC2noggsjjvU/OzUbJ+vnis5Dw4EKkEvnqnS+AuAEcqE1tsQKLvVNJ/DXrdz42LWPM6d++tIukQ+m8ZVqeAU0g+/od/jTjanRBykC0mcp7mQpFp5XQzhhL2qK7zDuZiRCV28qjKhalpFWjIHkiUmXfcPU+gAaQzp3Ea09oKA8+YvPk5LjB5Z/e7xsJr/qhHKhDqHowvcedU+w70IK1J4F2rXbidYHgkU2eFOYGGEKvkWZ3nZa1NzHziTpNTZ08MXoTZYxPD7+y66c46666JO25Ax84cj+pODGxo46Nead+C6NEcEPxFAEUWmhep/o53aqy08TQW1S/VY="
  distributions: "sdist bdist_wheel"
  server: https://test.pypi.org/legacy/
  on:
    all_branches: true