language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
before_deploy:
- make sphinx
- pip install --upgrade setuptools wheel
- python setup.py sdist bdist_wheel
deploy:
  skip_cleanup: true
  provider: pypi
  local-dir: docs/build/html
  github-token: PAGES_TOKEN
  keep-history: true
  user: PYPI_USERNAME
  password: PYPI_PASSWORD
  server: https://test.pypi.org/legacy/
  on:
    all_branches: true
env:
  global:
  - secure: WJpNVYHMqnI9feOedo22wxYMFBQJNr0Ggv7XlKpjNWRXZfhiQ9gZzXYwHmkz4H6r1tJIQqzWoIetEj9kRA6nArO5hVR2EiVjSgZcJefzawLdRUXMLx4FnkHcbHeQhDDefgPqhoxlPe6jEAaM6ND0JBRZtk+GFag9r/j2WhzzBZ73fxyPGsrDNH/UF7fht6NOiPzbY2/irO8QzkMwAPwVvs6bDjsm2+VZ5diAxUMlVTammoUNqO3hYn+X4eXIo+KyTsGthCfezvo9vjtJ4ojHPiyMCuNlFTjlblPA07kg8aiaWOfzE7hUxTif/J/JsykPCzvASmvnWjK2xJlz483Is5rycqWjX1YUoPqQpmVhUm7swfrKPopOveYw6lKzhBE97RpwAiSQFAn1KjwsqGFoq5s54TEgYPxWiasm2V9sMLJjSKmgBZuUG+o2aq08aRRnRtXzYtlbcbumCNhqWsQQzq1ABmz2Lo1qGtdpkul+jULnjLLnUD1LLzVZQEAQ45EWPtmOFUJuqjmyWRbIY5dw1+WMA/XV7DwG2ugbhswMpJF7AMLpjia46zVCGMS1z4gb+cUsIZ7JSYPEHkqUHomCOxR6YF4O+yhWEzNyaa/s9yW1Iveu65kzM9KXpyvtwn+wRSFc46z4QY3pplhQ56AN8nsXnVLvWy9lM30j7NQEo1Y=
  - secure: rX5/beI4nJkCWRtyuv4nknTOtVqqcmdTmZJlSfKIvGT4ExYRUM1QZL0CknnswW85anpPn6YyTSQJ3vBhuwG71vYILZBstnS2qxDlyWGdH+u/8mERdVjHaUGAnLYeKe5km8H84OXuwXi85DPr4lfab8KzPsCTxD3kaeaYKx4JY76CFwzxRtvB2KrWOgUX1lVfyVZIgBoWsXx9BxKL03F33NL+8PEaze1BmB9sfnN/AVQaERTGdtW7b/cVugc5UVpx5OeQbILT76JUMS4FA84gkJRCHiY3flKhlCn7x28/948Fx7CRgduyIcnXSOSKzYf4QRW3AgR1ldPg0um3kZItWft8PZguuBjavf5QRt7RyjNptyqLD9Hl0MMUvOdRY+ssDra5mlXWyVSejjUGnc2VRb3+59cqra9Jx16eHH4RHcpNlWtktC/D/H0DVuMt0b04TGz2D/Iwrbg186CsiTVUYEUHHQ4WGh2UfaF8w9L69ViFMwZcaQ6JVr/UKWsQk+F6i8dZ74JAmxEiq/2Y5i8xabF5G/oTGrHchGcdkpoUAsjVY8xkFL7DKB1lqg83tG+d9ylZpr0BCY8VkZlvHXDC9DEB38Sb45EiL+G/Rsk9QSLPLPFDHON4xZn/KQvsRPvkJ34usgCmARDKwrwnjqMkx7zIj226nVd+GlpTVfg7Mhk=
  - secure: A7jX/XnnP8kO42gG+fGs5OBxa2EM3UiE4/gF6jDhwW9VekmrXtdhzb40XIhrTwY/uyRd5lzoqrxAgYjGgt3rK13AqOcZfj+5s2CfrVVSfukGCOdtAUknNKOs+Acs+MIVF8uyeKoPSCBw3vPyDC0rxgbCrs1oWlXs2QSGj4+925Ty4590tv4bok5gMgg+wXyRpBv7l+JFWb+j8JmefjGZwXolq5iE0s1x3Im3Gcv4BBSWSaxomOFpWvs2qiiTi4PgKLyaWvyvzofRL4FmSMfal3MlABmv5j5xqsxVPCBKBsfPKFM+o9rD4wJ4JiGBb0fFMN2Z55upsU7Uhqd1rwWsgveKL8e/IZonU+DTucAnVmTZOUX1oJj7hUQzP4HDcagCKrp0cQsd8Rf79GSGdnjF0MkST0KzTyRXo5z/ysjwUF2EQTbRhGK1Gev6rKYpMexLt+nt/YoEU4RTuk0ZxEr95w1K+RR41mYkGz6LfsNTPuRrlAB1+JJKSp5+VTPZ7F0By4zP87J40QUs3dgYxErfzWMciOyQL26ZMN8r+X+wglThdHa9LP1J2A0/XIz+dQV4YynOk/TzN6I7KLHR0zQzCEMR/ysl1Wv7C20yzH7RynIS42ijQfQmXuRlTgDs/auni+mjk4eJYRKgHo/Vp+3GJdxhiWKin2Bw9u7I+qnOKUY=
